# Generated by Django 4.1.5 on 2023-01-17 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osauhing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osauhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('registry_code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('foundation_date', models.DateField(validators=[osauhing.models.validate_date])),
                ('capital', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(2500)])),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('personal_code', models.CharField(max_length=100)),
                ('ownership', models.DecimalField(decimal_places=0, max_digits=10)),
                ('isFounder', models.BooleanField(default=False)),
                ('parent_osauhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.osauhing')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registry_code', models.CharField(max_length=100)),
                ('ownership', models.DecimalField(decimal_places=0, max_digits=10)),
                ('isFounder', models.BooleanField(default=False)),
                ('parent_osauhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.osauhing')),
            ],
        ),
    ]
