# Generated by Django 4.1.5 on 2023-01-18 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osauhing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialLegalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')])),
                ('registry_code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='InitialPhysicalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')])),
                ('personal_code', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='Osauhing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')], verbose_name='Nimi')),
                ('registry_code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')], verbose_name='Registrikood')),
                ('foundation_date', models.DateField(validators=[osauhing.models.validate_date], verbose_name='Asutamiskuupäev')),
                ('capital', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(2500)], verbose_name='Kapitaal')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('isFounder', models.BooleanField(default=True)),
                ('initial_physical_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.initialphysicalpartner')),
                ('parent_osauhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.osauhing')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('isFounder', models.BooleanField(default=True)),
                ('initial_legal_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.initiallegalpartner')),
                ('parent_osauhing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osauhing.osauhing')),
            ],
        ),
    ]
